version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - MONGO_ADDRESS=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    networks:
      - auth-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

volumes:
  mongodb_data:
    driver: local

networks:
  auth-network:
    driver: bridge
