version: '3'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - "8084:8084"
    environment:
      - MONGO_ADDRESS=mongodb-chat
      - MONGO_PORT=27017
    depends_on:
      - mongodb-chat
    networks:
      - chat-network

  mongodb-chat:
    image: mongo:latest
    container_name: mongodb-chat
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_chat_data:/data/db
    networks:
      - chat-network

volumes:
  mongodb_chat_data:
    driver: local

networks:
  chat-network:
    driver: bridge